[workspace]
members = ["cargo:."]

[dist]
allow-dirty        = ["ci", "msi"]
cargo-dist-version = "0.28.0"
ci                 = "github"

# Rust target-triple syntax
targets = [
    "aarch64-apple-darwin",
    "aarch64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
    "x86_64-unknown-linux-gnu",
]
